# colors (miasma) https://github.com/xero/miasma.nvim
[colors]
indexed_colors = [{ index = 16, color = "0x181818"}]

# Primary colors
[colors.primary]
background = "#181818"
foreground = "#c2c2b0"

# Normal colors
[colors.normal]
black = "#181818"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

# Bright colors
[colors.bright]
black = "#606060"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"
